-- RETIRED: legacy duplicate cleanup was not scoped to synthetic identities.
-- It could collapse real repeated matches or assessments. Do not run deletion
-- queries from older revisions of this file. See docs/demo-data.md.
-- Current fixtures resume by exact deterministic IDs without a purge.
-- Any future cleanup requires an exact reviewed manifest and dependencies.
